//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miweb.Persistence.dataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.Orden_Producto = new HashSet<Orden_Producto>();
        }
    
        public int Ordid { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> DirId { get; set; }
        public Nullable<int> PagoId { get; set; }
        public Nullable<int> EnvId { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Envio Envio { get; set; }
        public virtual Pago Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_Producto> Orden_Producto { get; set; }
    }
}
